routes/admin.php
<?php
/**
 * Created by PhpStorm.
 * User: tongd
 * Date: 11/03/2018
 * Time: 10:26 SA
 */

Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'AdminLoginController@logout')->name('admin.logout.submit');
    Route::post('/forgot-password', 'AdminLoginController@logout')->name('admin.forgot-password.submit');

    Route::post('/password/email', 'AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset/{token}', 'AdminResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::post('/password/reset', 'AdminResetPasswordController@reset')->name('admin.password.admin-request');
});
Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');

Route::group(['namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {
    Route::resource('user-admins', 'UserAdminController')->except('show');

    Route::group(['namespace' => 'Cms', 'prefix' => 'cms-manager'], function () {
        Route::get('cms-subscribes', 'SubscribeController@index')->name('cms-subscribes.index');
//        Route::resource('cms-abouts', 'CmsAboutController', ['except' => 'show']);
        Route::group(['prefix' => 'cms-pages'], function () {
            Route::get('/', 'CmsPageController@index')->name('cms-pages.index');
            Route::get('create', 'CmsPageController@create')->name('cms-pages.create');
            Route::post('store', 'CmsPageController@store')->name('cms-pages.store');
            Route::get('{id}/edit', 'CmsPageController@edit')->name('cms-pages.edit');
            Route::post('update/{id}', 'CmsPageController@update')->name('cms-pages.update');
            Route::get('destroy/{id}', 'CmsPageController@destroy')->name('cms-pages.destroy');
        });
        Route::group(['prefix' => 'cms-articles'], function () {
            Route::get('/', 'CmsArticleController@index')->name('cms-articles.index');
            Route::get('create', 'CmsArticleController@create')->name('cms-articles.create');
            Route::post('store', 'CmsArticleController@store')->name('cms-articles.store');
            Route::get('{id}/edit', 'CmsArticleController@edit')->name('cms-articles.edit');
            Route::post('update/{id}', 'CmsArticleController@update')->name('cms-articles.update');
            Route::post('destroy/{id}', 'CmsArticleController@destroy')->name('cms-articles.destroy');
        });
        Route::group(['prefix' => 'cms-abouts'], function () {
            Route::get('/', 'CmsAboutController@index')->name('cms-abouts.index');
            Route::get('create', 'CmsAboutController@create')->name('cms-abouts.create');
            Route::post('store', 'CmsAboutController@store')->name('cms-abouts.store');
            Route::get('{id}/edit', 'CmsAboutController@edit')->name('cms-abouts.edit');
            Route::post('update/{id}', 'CmsAboutController@update')->name('cms-abouts.update');
            Route::get('destroy/{id}', 'CmsAboutController@destroy')->name('cms-abouts.destroy');
        });
        Route::group(['prefix' => 'cms-contacts'], function () {
            Route::get('/', 'CmsContactController@index')->name('cms-contacts.index');
            Route::get('create', 'CmsContactController@create')->name('cms-contacts.create');
            Route::post('store', 'CmsContactController@store')->name('cms-contacts.store');
            Route::get('{id}/edit', 'CmsContactController@edit')->name('cms-contacts.edit');
            Route::post('update/{id}', 'CmsContactController@update')->name('cms-contacts.update');
            Route::post('destroy/{id}', 'CmsContactController@destroy')->name('cms-contacts.destroy');
        });
        Route::group(['prefix' => 'cms-categories'], function () {
            Route::get('/', 'CmsCategoryController@index')->name('cms-categories.index');
            Route::get('create', 'CmsCategoryController@create')->name('cms-categories.create');
            Route::post('store', 'CmsCategoryController@store')->name('cms-categories.store');
            Route::get('{id}/edit', 'CmsCategoryController@edit')->name('cms-categories.edit');
            Route::post('update/{id}', 'CmsCategoryController@update')->name('cms-categories.update');
            Route::post('destroy/{id}', 'CmsCategoryController@destroy')->name('cms-categories.destroy');
            Route::post('get-cate-by-objectname', 'CmsCategoryController@getCateByObjectName')->name('get-cate-by-objectname');
        });
        Route::group(['prefix' => 'cms-feedbacks'], function () {
            Route::get('/', 'CmsFeedbackController@index')->name('cms-feedbacks.index');
            Route::get('{id}/edit', 'CmsFeedbackController@edit')->name('cms-feedbacks.edit');
            Route::post('update/{id}', 'CmsFeedbackController@update')->name('cms-feedbacks.update');
            Route::post('destroy/{id}', 'CmsFeedbackController@destroy')->name('cms-feedbacks.destroy');
        });
        Route::group(['prefix' => 'cms-services'], function () {
            Route::get('/', 'CmsServiceController@index')->name('cms-services.index');
            Route::get('create', 'CmsServiceController@create')->name('cms-services.create');
            Route::post('store', 'CmsServiceController@store')->name('cms-services.store');
            Route::get('{id}/edit', 'CmsServiceController@edit')->name('cms-services.edit');
            Route::post('update/{id}', 'CmsServiceController@update')->name('cms-services.update');
            Route::post('destroy/{id}', 'CmsServiceController@destroy')->name('cms-services.destroy');
        });
        Route::group(['prefix' => 'cms-slides'], function () {
            Route::get('/', 'CmsSlideController@index')->name('cms-slides.index');
            Route::get('create', 'CmsSlideController@create')->name('cms-slides.create');
            Route::post('store', 'CmsSlideController@store')->name('cms-slides.store');
            Route::get('{id}/edit', 'CmsSlideController@edit')->name('cms-slides.edit');
            Route::post('update/{id}', 'CmsSlideController@update')->name('cms-slides.update');
            Route::post('destroy/{id}', 'CmsSlideController@destroy')->name('cms-slides.destroy');
        });
        Route::group(['prefix' => 'cms-slide-element'], function () {
            Route::match(['post', 'get'], '/', 'CmsSlideElementController@index')->name('cms-slide-elements.index');
            Route::get('create', 'CmsSlideElementController@create')->name('cms-slide-elements.create');
            Route::post('store', 'CmsSlideElementController@store')->name('cms-slide-elements.store');
            Route::get('{id}/edit', 'CmsSlideElementController@edit')->name('cms-slide-elements.edit');
            Route::post('update/{id}', 'CmsSlideElementController@update')->name('cms-slide-elements.update');
            Route::post('destroy/{id?}', 'CmsSlideElementController@destroy')->name('cms-slide-elements.destroy');
        });
        Route::group(['prefix' => 'cms-faq'], function () {
            Route::match(['post', 'get'], '/', 'CmsFaqController@index')->name('cms-faqs.index');
            Route::get('create', 'CmsFaqController@create')->name('cms-faqs.create');
            Route::post('store', 'CmsFaqController@store')->name('cms-faqs.store');
            Route::get('{id}/edit', 'CmsFaqController@edit')->name('cms-faqs.edit');
            Route::post('update/{id}', 'CmsFaqController@update')->name('cms-faqs.update');
            Route::post('destroy/{id?}', 'CmsFaqController@destroy')->name('cms-faqs.destroy');
        });
        Route::group(['prefix' => 'cms-partner'], function () {
            Route::match(['post', 'get'], '/', 'CmsPartnerController@index')->name('cms-partners.index');
            Route::get('create', 'CmsPartnerController@create')->name('cms-partners.create');
            Route::post('store', 'CmsPartnerController@store')->name('cms-partners.store');
            Route::get('{id}/edit', 'CmsPartnerController@edit')->name('cms-partners.edit');
            Route::post('update/{id}', 'CmsPartnerController@update')->name('cms-partners.update');
            Route::post('destroy/{id?}', 'CmsPartnerController@destroy')->name('cms-partners.destroy');
        });
        Route::group(['prefix' => 'cms-statistic'], function () {
            Route::match(['post', 'get'], '/', 'CmsStatisticController@index')->name('cms-statistics.index');
            Route::get('create', 'CmsStatisticController@create')->name('cms-statistics.create');
            Route::post('store', 'CmsStatisticController@store')->name('cms-statistics.store');
            Route::get('{id}/edit', 'CmsStatisticController@edit')->name('cms-statistics.edit');
            Route::post('update/{id}', 'CmsStatisticController@update')->name('cms-statistics.update');
            Route::post('destroy/{id?}', 'CmsStatisticController@destroy')->name('cms-statistics.destroy');
        });
        Route::group(['prefix' => 'cms-testimonial'], function () {
            Route::match(['post', 'get'], '/', 'CmsTestimonialController@index')->name('cms-testimonials.index');
            Route::get('create', 'CmsTestimonialController@create')->name('cms-testimonials.create');
            Route::post('store', 'CmsTestimonialController@store')->name('cms-testimonials.store');
            Route::get('{id}/edit', 'CmsTestimonialController@edit')->name('cms-testimonials.edit');
            Route::post('update/{id}', 'CmsTestimonialController@update')->name('cms-testimonials.update');
            Route::post('destroy/{id?}', 'CmsTestimonialController@destroy')->name('cms-testimonials.destroy');
        });
        Route::group(['prefix' => 'cms-portfolio'], function () {

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('check-user/{token}', function ($token) {
    $user = \App\Admin::where('token', $token)->first();
    if ($user) {
        $user->token = null;
        $user->is_active = 1;
        $user->save();
        return redirect(route('admin.login'));
    }
    return redirect(route('web.index'));
})->name('user.check-user');

/*Route::get('/', function () {
    return view('welcome');
});*/

$suffix = '.html';

Route::group(['namespace' => 'Client'], function () use ($suffix) {

    Route::get('/', 'PageController@index')->name('index')->middleware('countview');
    Route::get('about-us' . $suffix, 'PageController@about')->name('about')->middleware('countview');
    Route::match(['get', 'post'], 'contact' . $suffix, 'PageController@contact')->name('contact')->middleware('countview');
    Route::get('blog' . $suffix, 'BlogController@blog')->name('blog')->middleware('countview');
    Route::get('blog/category/{slug}' . $suffix, 'BlogController@blogCategory')->name('blog-category')->middleware('countview');
    Route::get('blog/{slug}' . $suffix, 'BlogController@blogDetail')->name('blog-detail')->middleware('countview');
    Route::get('portfolio' . $suffix, 'PageController@portfolio')->name('portfolio')->middleware('countview');
    Route::get('bus-schedule' . $suffix, 'PageController@busSchedule')->name('bus-schedule')->middleware('countview');
    Route::get('carasia-rental' . $suffix, 'PageController@carasiaRental')->name('carasia-rental')->middleware('countview');
    Route::get('booking/{trip?}', 'PageController@booking')->name('booking')->middleware('countview');
    Route::get('contact-us' . $suffix, 'PageController@contact')->name('contact')->middleware('countview');
    Route::get('faqs' . $suffix, 'PageController@faq')->name('faq')->middleware('countview');
    Route::get('terms-and-conditions' . $suffix, 'PageController@term')->name('term')->middleware('countview');
    Route::get('contact-us/store' . $suffix, 'ContactController@store')->name('contact.store')->middleware('countview');

    Route::group(['prefix' => 'cms-subscribe'], function () {
        Route::get('/', 'SubscribeController@index')->name('cms-subscribes.index')->middleware('countview');
        Route::post('store', 'SubscribeController@store')->name('cms-subscribes.store');
    });
});

/*************************PAYMENT***********************************/

Route::group(['prefix' => 'payment', 'namespace' => 'Client'], function () use ($suffix) {

    Route::post('handle-booking', 'AlepayController@handleBooking')->name('payment.handle-booking');
    Route::match(['get', 'post'], 'checkout-step1' . $suffix, 'AlepayController@checkoutStep1')->name('payment.checkout-step1');
    Route::get('checkout-step2' . $suffix, 'AlepayController@checkoutStep2')->name('payment.checkout-step2');
    Route::get('empty-booking' . $suffix, 'AlepayController@emptyBooking')->name('payment.empty-booking');
    Route::get('handle-payment' . $suffix, 'AlepayController@handlePayment')->name('payment.handle-payment');
    Route::get('result' . $suffix, 'AlepayController@result')->name('payment.result');
    Route::get('booking-detail/{order_code}-{transaction_code}' . $suffix, 'AlepayController@bookingDetail')->name('payment.booking-detail');

});

/*Route::post('checkout', 'CheckOutNlController@checkout')->name('checkout');
Route::get('checkout-success/{id}', 'CheckOutNlController@checkoutSuccess')->name('checkout-success');
Route::get('booking-detail-qr/{order_code}', 'CheckOutNlController@bookingQrCode')->name('booking-detail-qr');
Route::any('payment-success', 'CheckOutNlController@paymentSuccess')->name('payment-success');
Route::get('cancel-url/{id}', 'CheckOutNlController@cancelUrl')->name('cancel-url');*/

/*Route::group(['prefix' => 'paypal'], function () {
    Route::post('/', 'PayPalController@index')->name('paypal.index');
    Route::get('status', 'PayPalController@status')->name('paypal.status');
    Route::get('detail/{id}', 'PayPalController@paymentDetail')->name('paypal.detail');
    Route::get('lists', 'PayPalController@paymentList')->name('paypal.lists');
});*/


Route::get('routes', function () {
    $routeCollection = Route::getRoutes();

    echo "<table style='width:100%'>";
    echo "<tr>";
    echo "<td width='10%'><h4>HTTP Method</h4></td>";
    echo "<td width='10%'><h4>Route</h4></td>";
    echo "<td width='10%'><h4>Name</h4></td>";
    echo "<td width='70%'><h4>Corresponding Action</h4></td>";
    echo "</tr>";
    foreach ($routeCollection as $value) {
        if (strpos($value->uri(), 'admin') !== 0) {
            echo "<tr>";
            echo "<td>" . json_encode($value->methods()) . "</td>";
            echo "<td>" . $value->uri() . "</td>";
            echo "<td>" . $value->getName() . "</td>";
            echo "<td>" . $value->getActionName() . "</td>";
            echo "</tr>";
        }
    }
    echo "</table>";
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/*Route::get('/mail', function () {
    $dataSendMail = [
        'transaction_code' => 'transaction_code',
        'order_code' => 'order_code',
        'name' => 'name',
        'email' => 'email',
        'phone' => 'phone',
        'address' => 'address',
        'time_departure' => 'time_departure',
        'time_arrival' => 'time_arrival',
        'flight_number' => 'flight_number',
        'quantity_adult' => 'quantity_adult',
        'quantity_child' => 'quantity_child',
        'departure_date' => 'departure_date',
        'return_date' => 'return_date',
        'booking_type' => 'booking_type',
        'booking_status' => 'booking_status',
        'booking_note' => 'booking_note',
        'payment_method' => 'payment_method',
        'payment_status' => 'payment_status',
        'booking_detail' =>  'https://www.car-asia.com.vn/carasia-rental'
    ];

    \Illuminate\Support\Facades\Mail::send('test', $dataSendMail, function ($message) {
        $message->to('tongduc315@gmail.com');
        $message->subject('Car - Asia RESERVATION #' . 'transaction_code');
    });
});*/

resources/views/admin/user-manager/active.blade.php
<label class="switch">
    <input type="checkbox" {{ ($active) ? 'checked' : '' }}>
    <span class="slider round"></span>
</label>

resources/views/admin/user-manager/create.blade.php
@extends('layouts.app-admin')

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <form action="{{ route('user-admins.store') }}" method="post">
                            @csrf
                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#general">{{ __('General') }}</a></li>
                            </ul>

                            <div class="tab-content">
                                <div id="general" class="tab-pane fade in active">
                                    <br>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>{{ __('Name') }}:
                                                    <span class="required text-danger"> * </span>
                                                </label>
                                                <input type="text" class="form-control"
                                                       name="name"
                                                       required
                                                       value="{{ old('name') }}"
                                                       placeholder="{{ __('Enter name') }}">
                                                <span class="help-block"> Max length 191 chars </span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>{{ __('Email') }}:
                                                    <span class="required text-danger"> * </span>
                                                </label>
                                                <input type="email" class="form-control"
                                                       name="email"
                                                       required
                                                       value="{{ old('email') }}"
                                                       placeholder="{{ __('Enter email') }}">
                                                <span class="help-block"> Max length 191 chars </span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>{{ __('Type') }}:
                                                    <span class="required text-danger"> * </span>
                                                </label>
                                                <select name="type" class="form-control">
                                                    @foreach(ROLES as $item)
                                                        <option value="{{ $item }}">{{ $item }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button class="btn btn-success" type="submit" name="btnSubmit">Submit</button>
                                    <input class="btn btn-default" type="reset" value="Reset">
                                    <a href="{{ route('user-admins.index') }}" class="btn btn-danger">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/admin/user-manager/edit.blade.php
@extends('layouts.app-admin')

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        {!! Form::model($user, ['method' => 'PATCH', 'route' => ['user-admins.update', $user->id]]) !!}
                            @csrf
                            @method('PUT')
                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#general">{{ __('General') }}</a></li>
                            </ul>

                            <div class="tab-content">
                                <div id="general" class="tab-pane fade in active">
                                    <br>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>{{ __('Name') }}:
                                                    <span class="required text-danger"> * </span>
                                                </label>
                                                {!! Form::text('name', old('name'),['class' => 'form-control']) !!}
                                                <span class="help-block"> Max length 191 chars </span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>{{ __('Email') }}:
                                                    <span class="required text-danger"> * </span>
                                                </label>
                                                {!! Form::text('email', old('email'),['class' => 'form-control']) !!}
                                                <span class="help-block"> Max length 191 chars </span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label>{{ __('Type') }}:
                                                    <span class="required text-danger"> * </span>
                                                </label>
                                                {!! Form::select('type', ROLES, old('type'), ['class' => 'form-control']) !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button class="btn btn-success" type="submit" name="btnSubmit">Submit</button>
                                    <input class="btn btn-default" type="reset" value="Reset">
                                    <a href="{{ route('user-admins.index') }}" class="btn btn-danger">Cancel</a>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/admin/user-manager/index.blade.php
@extends('layouts.app-admin')

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <div class="pull-left">
                            <a href="{{ route('user-admins.create') }}" class="btn btn-success "><i class="fa fa-plus-square"></i> <strong>Create</strong></a>

                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-bordered table-hover" id="users-table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Type</th>
                                <th>Active</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('style')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
@endsection

@section('script')
    <!-- DataTables -->
    <script src="https://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>

    <script>
        $(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('user-admins.index') !!}',
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'type', name: 'type'},
                    {data: 'is_active', name: 'is_active', orderable: true, searchable: false},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            });
            $.fn.dataTable.ext.errMode = 'throw';
        });
    </script>

@endsection